on:
  push:
    branches:
      - static

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install
          yarn build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to S3
        run: aws s3 cp ./out s3://$AWS_S3_BUCKET --acl public-read --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
